### ISSUE TITLE
elem_match cannot find documents when using string for object id

### ISSUE THREAD

**Issue by calfzhou** [mongoid/mongoid#3977]
mongoid v4.0.2

I have a NxN relationship and the relation is `embeds_many` into one collection, say, I have two collections Foo and Bar, and their relationships Relation.

```ruby
class Foo
  embeds_many :relations
end

class Bar
end

class Relation
  embedded_in :Foo
  belongs_to :Bar
end
```

Then i might have some documents
```yaml
- 
  _id: foo1
  data: blah blah
  relations:
    -
      _id: rel1
      bar_id: bar1
    -
      _id: rel2
     bar_id: bar2
- 
  _id: foo2
  data: whatever
  relations:
    -
      _id: rel3
     bar_id: bar2
```

Now i'd like to find all `Foo`s which has relation to `bar1` (an object id), if i run `Foo.elem_match(relations: { bar_id: 'bar1' }).first` will return nil. But `Foo.elem_match(relations: { bar_id: BSON::ObjectId.from_string('bar1') }).first` will return document `foo1`.

Is there any way to make the former statement work?
