### ISSUE TITLE
Suggested fix for errors in mongoid.yml mention Rails

### ISSUE THREAD

**Issue by dblock** [mongoid/mongoid#4118]
Resolution talks about Rails, not everybody uses Rails.

_ Double check your mongoid.yml to make sure that you have a top-level clients key with at least 1 default client configuration for it. You can regenerate a new mongoid.yml for assistance via `rails g mongoid:config`._

```
/Users/dblock/.rvm/gems/ruby-2.1.2/gems/mongoid-5.0.0.beta/lib/mongoid/config.rb:252:in `clients=':  (Mongoid::Errors::NoClientsConfig)
Problem:
  No clients configuration provided.
Summary:
  Mongoid's configuration requires that you provide details about each client that can be connected to, and requires in the clients config at least 1 default client to exist.
Resolution:
  Double check your mongoid.yml to make sure that you have a top-level clients key with at least 1 default client configuration for it. You can regenerate a new mongoid.yml for assistance via `rails g mongoid:config`.

 Example:
   development:
     clients:
       default:
         database: mongoid_dev
         hosts:
           - localhost:27017

	from /Users/dblock/.rvm/gems/ruby-2.1.2/gems/mongoid-5.0.0.beta/lib/mongoid/config.rb:131:in `load_configuration'
	from /Users/dblock/.rvm/gems/ruby-2.1.2/gems/mongoid-5.0.0.beta/lib/mongoid/config.rb:88:in `load!'
	from /Users/dblock/.rvm/gems/ruby-2.1.2/gems/mongoid-5.0.0.beta/lib/mongoid.rb:106:in `load!'

```

**Comment by danilovaz** [comment]
Hey guys,

Any news on this subject? My application was functioning normally under development; I run it today and appeared the same message described above.

I use mongodb 2.6

My configuration:
```
development:
  # Configure available database sessions. (required)
  sessions:
    # Defines the default session. (required)
    default:
      # Defines the name of the default database that Mongoid can connect to.
      # (required).
      database: name_database
      username: "username"
      password: "password"
      # Provides the hosts the default session can connect to. Must be an array
      # of host:port pairs. (required)
      hosts:
        - 127.0.0.1:27017
```
In my gemfile was setted: 
```
gem 'mongoid', git: 'git://github.com/mongoid/mongoid.git' 
```
So I change it for and works fine now:

```
gem 'mongoid', '~> 4.0.2'
```
