### ISSUE TITLE
MongoDB replica set connection not closed

### ISSUE THREAD

**Issue by vecio** [mongoid/mongoid#4130]
In unicorn worker and sidekiq worker, all mongodb connections not closed. Will reach more than 1M MongoDB connections

```
ruby      25127 25364     webapp  130u     IPv4          357685236       0t0       TCP api-1.c.shou-tv.internal:49807->mongodb-rs1.c.shou-tv.internal:27017 (ESTABLISHED)
ruby      25127 25364     webapp  132u     IPv4          357679837       0t0       TCP api-1.c.shou-tv.internal:49809->mongodb-rs1.c.shou-tv.internal:27017 (ESTABLISHED)
```

They only connect to primary although I configure it to read secondary.

**Comment by durran** [comment]
Can you have a look at this comment and then provide me with more information please...

https://github.com/mongoid/mongoid/issues/4128#issuecomment-121521340

**Comment by vecio** [comment]
I don't use some special args like that issue, and the mongoid.yml is below

```yaml
production:
  clients:
    default:
      database: db_production
      hosts:
        - mongodb-rs1:27017 # This is the primary
        - mongodb-rs0:27017 # This is secondary
        - mongodb-rs2:27017 # This is secondary
      options:
        write:
          w: 1
        read:
          mode: :secondary
        heartbeat_frequency: 5
        server_selection_timeout: 10
        max_pool_size: 128
        min_pool_size: 32
        wait_queue_timeout: 5
        connect_timeout: 5
        socket_timeout: 5
        replica_set: rs0
  options:
    include_root_in_json: true
    scope_overwrite_exception: true
    use_utc: false
```
